name: "Youtube"

services:
  db:
    image: mysql:8.0.40-debian
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: yt_db
      MYSQL_USER: youtube_db_user
      MYSQL_PASSWORD: youtube123
      MYSQL_ROOT_PASSWORD: root
      
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    networks:
      - myproject_network

  redis:
    image: redis:latest
    container_name: redis_cache
    networks:
      - myproject_network

  django1:
    build: .
    container_name: django1_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - myproject_network
  django2:
    build: .
    container_name: django2_server
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - myproject_network
  django3:
    build: .
    container_name: django3_server
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - myproject_network

  apache:
    build: ./apache
    container_name: apache_loadbalancer
    ports:
      - "80:80"
    depends_on:
      - django1
      - django2
      - django3
    networks:
      - myproject_network


volumes:
  mysql_data:

networks:
  myproject_network:
    driver: bridge